### ISSUE TITLE
Issue using a fork of the repository

### ISSUE THREAD

**Issue by RajaBellebon** [gidztech/jest-puppeteer-docker#14]
Hello @gidztech,

As we had dedicated need in our repo, I wanted to fork yours and use our own debian image running on node 8.9.0 ->` atlassianlabs/atlaskit-mk-2:1.0.4`.

I updated couple of lines to adapt your two docker containers - see -> https://github.com/RajaBellebon/jest-puppeteer-docker

When in my project, I used the forked repo, I got:
```
  Jest Puppeteer Docker: Setting Chromium version to rev-599821...
  Jest Puppeteer Docker: Building Docker image...
  Jest Puppeteer Docker: Failed to build Docker image from repository, now trying tobuild from scratch.
  This will take some time...
```

and it loops for a time.

But if I am back to my fork and I do docker build && docker compose no issue...

Any help would be really appreciated!

Thanks in advance,

Raja

**Comment by RajaBellebon** [comment]
In addition, sometimes, in the fork, when I do `docker-compose up` it fails with:

```
Creating docker_chromium_alternative_1 ... error
Creating docker_chromium_1             ...

ERROR: for docker_chromium_alternative_1  Cannot start service chromium_alternative: driver failed programming external connectivity on endpoint docker_chromium_alternative_1 (8c79e6ab38d5f464648b351fCreating docker_chromium_1             ... done

ERROR: for chromium_alternative  Cannot start service chromium_alternative: driver failed programming external connectivity on endpoint docker_chromium_alternative_1 (8c79e6ab38d5f464648b351fc022f311bd657eef4dd4b4c70f0981176c5ea0ab): Bind for 0.0.0.0:9222 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Comment by gidztech** [comment]
I pulled the forked repository and the tests ran after a while - the build of the container takes some time. The tests for me failed due to rendering differences in the new image but that's to be expected. 

The binding lock-up sounds like an issue with the process not ending properly. You might want to restart your Docker service to fix that.

I'm not really supporting custom images currently. I've recently split out the Docker/connection logic into a new repository, which consequently will make it more difficult for you to customize, but meant I could re-use the logic in other applications without Jest. See https://github.com/gidztech/docker-chromium

I may look into providing an API that allows you to pass in custom Docker config, but will require a bit of work.

**Comment by RajaBellebon** [comment]
ok @gidztech thanks for looking into it, keep me posted!
